### ISSUE TITLE
emqx接受到消息执行emqx_plugin_kafka插件报错

### ISSUE THREAD

**Issue by fengyouwei** [ULTRAKID/emqx_plugin_kafka#1]
我这边根据https://github.com/ULTRAKID/emqx 分支版本为main-v4.3构建成功并启动，开始发送消息到emqx时执行emqx_plugin_kafka插件报错。报错信息如下：
[error] mqttx_734cc423@192.168.99.159:49010 [Hooks] Failed to execute {emqx_plugin_kafka,on_message_publish,[[{broker,[{host,"172.16.3.168"},{port,"9092"},{partitionstrategy,"strict_round_robin"},{partitionworkers,1},{payloadtopic,"device_topic"}]}]]}: {exit,{{undef,[{pg2,create,[<<"ekaf.device_topic">>],[]},{ekaf_server,init,1,[{file,"ekaf_server.erl"},{line,69}]},{gen_fsm,init_it,6,[{file,"gen_fsm.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{gen_fsm,sync_send_event,[<0.2330.0>,prepare]}},[{gen_fsm,sync_send_event,2,[{file,"gen_fsm.erl"},{line,229}]},{ekaf_lib,prepare,2,[{file,"ekaf_lib.erl"},{line,55}]},{ekaf_lib,common_async,3,[{file,"ekaf_lib.erl"},{line,98}]},{emqx_plugin_kafka,on_message_publish,2,[{file,"emqx_plugin_kafka.erl"},{line,183}]},{emqx_hooks,safe_execute,2,[{file,"emqx_hooks.erl"},{line,191}]},{emqx_hooks,do_run_fold,3,[{file,"emqx_hooks.erl"},{line,170}]},{emqx_broker,publish,1,[{file,"emqx_broker.erl"},{line,204}]},{emqx_channel,do_publish,3,[{file,"emqx_channel.erl"},{line,578}]},{emqx_connection,with_channel,3,[{file,"emqx_connection.erl"},{line,664}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,364}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,370}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,328}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}]}

配置信息为：

###kafka.port = 9092
kafka.port = 9092

## The kafka loadbalancer node partition strategy.
##--------------------------------------------------------------------
## kafka Bridge
##--------------------------------------------------------------------

##
## Value: 127.0.0.1, localhost
###kafka.host = 192.168.67.16
kafka.host = 172.16.3.168

##
## Value: Port
###kafka.port = 9092
kafka.port = 9092

##
## Value: random, sticky_round_robin, strict_round_robin, custom
kafka.partitionstrategy = strict_round_robin

##
## Value:
kafka.partitionworkers = 1

##
## Value: string
kafka.payloadtopic = device_topic

请问下我这边哪里出了问题，请指正。谢谢！

**Comment by ULTRAKID** [comment]
看起来似乎是与kafka的连接有问题。

1. emqx所在服务器或者容器内是否能连通该kafka节点？
2. 用kafka工具手动往该kafka的这个topic发送消息是否能成功？

**Comment by fengyouwei** [comment]
以上2点都没有问题，emqx所在服务器能连接kafka节点（kafka单节点部署），并能成功发送、接受消息（已在emqx服务器测试）。

**Comment by ULTRAKID** [comment]
可以加我微信详细沟通一下
微信号是： ultrakid_ccc

**Comment by ULTRAKID** [comment]
是否使用了erlang OTP 24或以上的版本？
![image](https://user-images.githubusercontent.com/28863299/159831477-315c929e-0e4d-418b-93b9-f7a718ceb4dd.png)

**Comment by fengyouwei** [comment]
由于emqx需要erlang23以上版本，所以正常使用只能使用23版本进行编译。此消息仅做记录省去后来者沟通成本。
