### ISSUE TITLE
请问下转发到kafka的规则怎么写

### ISSUE THREAD

**Issue by echolevan** [ULTRAKID/emqx_plugin_kafka#2]

**Comment by ULTRAKID** [comment]
启用该插件，并且修改该插件配置文件里对应的kafka地址和topic即可转发

**Comment by echolevan** [comment]
在容器内，telnet 能通。但是 netstat查看都是ESTABLISHED 。

**Comment by ULTRAKID** [comment]
没有明白你表达的意思，是和kafka的地址能telnet痛，然后和kafka的连接是ESTABLISHED吗？（ESTABLISHED是正常连接的状态）
现在是客户端连接emqx或者发送消息之后kafka没有消息转发吗？
