### ISSUE TITLE
升级到brod后，配置文件问题。

### ISSUE THREAD

**Issue by z20081120087** [ULTRAKID/emqx_plugin_kafka#4]
使用Releases中的4.3.12.5版本（ekaf）时，直接修改plugin下的配置文件即可。能正常使用。
但是4.3.12.6和7版本中，未找到该配置文件，emqx dashboard中也无法启动该插件。报错：parse_config_file_failed
docker logs：

2023-02-21T06:32:10.749386+00:00 [error] supervisor: {local,brod_sup}, errorContext: child_terminated, reason: [{{"localhost",9092},{econnrefused,[{kpro_connection,connect,4,[{file,"kpro_connection.erl"},{line,208}]},{kpro_connection,init,4,[{file,"kpro_connection.erl"},{line,170}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}}], offender: [{pid,<0.3742.0>},{id,emqx_repost_worker},{mfargs,{brod_client,start_link,[[{"localhost",9092}],emqx_repost_worker,[{reconnect_cool_down_seconds,10},{query_api_versions,true}]]}},{restart_type,{permanent,10}},{shutdown,5000},{child_type,worker}]

**Comment by ULTRAKID** [comment]
https://github.com/ULTRAKID/emqx_plugin_kafka/blob/main/etc/emqx_plugin_kafka.config

**Comment by ULTRAKID** [comment]
> https://github.com/ULTRAKID/emqx_plugin_kafka/blob/main/etc/emqx_plugin_kafka.config

@z20081120087 4.3.12.6和7版本需要用新的配置文件，引用的配置文件名称改了，不好意思

**Comment by z20081120087** [comment]
我在docker容器中的etc/plugin目录下创建了这个文件，再次开启的提示变成了：
{emqx_plugin_kafka,{bad_return,{{emqx_plugin_kafka_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,already_present}},[{emqx_plugin_kafka,kafka_init,1,[{file,"emqx_plugin_kafka.erl"},{line,272}]},{emqx_plugin_kafka,load,1,[{file,"emqx_plugin_kafka.erl"},{line,61}]},{emqx_plugin_kafka_app,start,2,[{file,"emqx_plugin_kafka_app.erl"},{line,29}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,277}]}]}}}}}

**Comment by ULTRAKID** [comment]
重启emqx还是提示这个吗？

**Comment by ULTRAKID** [comment]
不光是重启插件

**Comment by z20081120087** [comment]
我重启了整个容器，开启插件报错如下：
{emqx_plugin_kafka,{bad_return,{{emqx_plugin_kafka_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{client_down,[{{"192.168.1.134",9092},{ehostunreach,[{kpro_connection,connect,4,[{file,"kpro_connection.erl"},{line,208}]},{kpro_connection,init,4,[{file,"kpro_connection.erl"},{line,170}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}}]}}},[{emqx_plugin_kafka,kafka_init,1,[{file,"emqx_plugin_kafka.erl"},{line,273}]},{emqx_plugin_kafka,load,1,[{file,"emqx_plugin_kafka.erl"},{line,61}]},{emqx_plugin_kafka_app,start,2,[{file,"emqx_plugin_kafka_app.erl"},{line,29}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,277}]}]}}}}}

**Comment by ULTRAKID** [comment]
完整的配置文件贴一下呢

**Comment by z20081120087** [comment]
bash-5.0$ cat emqx_plugin_kafka.config 
[
    {emqx_plugin_kafka, [
        {kafka_address_list, [{"192.168.1.134", 9092}]},    %% kafka地址，可配置多个
        {kafka_config, [                                %% 这部分是https://github.com/kafka4beam/brod库需要的配置
            {reconnect_cool_down_seconds, 10},          %% socket error recovery
            {query_api_versions, true}                  %% Kafka 0.9.x or Earlier请设置为false
        ]},
        {topic, <<"emqx-topic">>},                           %% 转发的目标topic
        {publish_base64, false}                         %% 对于publish到mqtt的消息内容，是否进行base64编码之后再转发（为了兼容发送字节流的情况）
    ]}
].

**Comment by ULTRAKID** [comment]
这个错应该就只是连接问题，方便的话加我微信看看 ultrakid_ccc

**Comment by ULTRAKID** [comment]
kafka服务端本身存在问题
