### ISSUE TITLE
点击启用kafka插件报错 parse_config_file_failed

### ISSUE THREAD

**Issue by allure11** [ULTRAKID/emqx_plugin_kafka#5]
![image](https://github.com/ULTRAKID/emqx_plugin_kafka/assets/86544479/ef1c58b9-1437-4097-8e72-1a12ab484592)

/emqx/_build/emqx/rel/emqx/etc/plugins
```
    [
      { emqx_plugin_kafka,[
          { kafka_address_list, [ { "172.28.57.6", 9093 } ] },
      { kafka_config, [
          { reconnect_cool_down_seconds, 10 },
      { query_api_versions, true },
      ]},
      { topic,<<"emqx-topic">> }
      ]}
    ]
```

**Comment by ULTRAKID** [comment]
配置文件名称后缀是config还是conf？
可以的话再贴一下后台的报错日志🧐

**Comment by allure11** [comment]
配置文件名称：emqx_plugin_kafka.conf

报错日志：
2024-06-27T05:39:18.266196+00:00 [alert] [Plugins] Plugin emqx_plugin_kafka load failed with {{schema_not_found,"/home/emqx/_build/emqx/rel/emqx/lib/emqx_plugin_kafka-0.0.0+build.1.refe23cc37/priv/emqx_plugin_kafka.schema"},[{emqx_plugins,do_generate_configs,1,[{file,"emqx_plugins.erl"},{line,274}]},{emqx_plugins,load_plugin,2,[{file,"emqx_plugins.erl"},{line,299}]},{emqx_mgmt_api_plugins,load,2,[{file,"emqx_mgmt_api_plugins.erl"},{line,78}]},{minirest_handler,dispatch,2,[{file,"minirest_handler.erl"},{line,90}]},{minirest,handle_request,2,[{file,"minirest.erl"},{line,116}]},{minirest,init,2,[{file,"minirest.erl"},{line,108}]},{cowboy_handler,execute,2,[{file,"cowboy_handler.erl"},{line,41}]},{cowboy_stream_h,execute,3,[{file,"cowboy_stream_h.erl"},{line,320}]},{cowboy_stream_h,request_process,3,[{file,"cowboy_stream_h.erl"},{line,302}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}

**Comment by ULTRAKID** [comment]
后缀名称改成config

**Comment by allure11** [comment]
修改配置文件为 config 后缀之后，emqx无法启动

`root@9b9b28990650:/home/emqx/_build/emqx/rel/emqx/bin# ./emqx console
log.to = "console"
Erlang/OTP 24 [erts-12.2.1] [emqx] [64-bit] [smp:8:8] [ds:8:8:8] [async-threads:4] [jit]

Starting emqx on node emqx@127.0.0.1
2024-06-27T06:27:15.499847+00:00 [warning] [Alarm Handler] Alarm high_system_memory_usage is activated, System memory usage is higher than 70.0%
Start mqtt:tcp:internal listener on 127.0.0.1:11883 successfully.
Start mqtt:tcp:external listener on 0.0.0.0:1883 successfully.
Start mqtt:ws:external listener on 0.0.0.0:8083 successfully.
Start mqtt:ssl:external listener on 0.0.0.0:8883 successfully.
Start mqtt:wss:external listener on 0.0.0.0:8084 successfully.
2024-06-27T06:27:15.505038+00:00 [error] crasher: initial call: application_master:init/4, pid: <0.1637.0>, registered_name: [], exit: {{bad_return,{{emqx_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{7,erl_parse,["syntax error before: ","']'"]}}},[{emqx_plugins,init_config,1,[{file,"emqx_plugins.erl"},{line,148}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{emqx_app,start,2,[{file,"emqx_app.erl"},{line,49}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,293}]}]}}}},[{application_master,init,4,[{file,"application_master.erl"},{line,142}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}, ancestors: [<0.1636.0>], message_queue_len: 1, messages: [{'EXIT',<0.1638.0>,normal}], links: [<0.1636.0>,<0.1494.0>], dictionary: [], trap_exit: true, status: running, heap_size: 987, stack_size: 29, reductions: 301; neighbours:
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
{"Kernel pid terminated",application_controller,"{application_start_failure,emqx,{bad_return,{{emqx_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{7,erl_parse,[\"syntax error before: \",\"']'\"]}}},[{emqx_plugins,init_config,1,[{file,\"emqx_plugins.erl\"},{line,148}]},{lists,foreach,2,[{file,\"lists.erl\"},{line,1342}]},{emqx_app,start,2,[{file,\"emqx_app.erl\"},{line,49}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,293}]}]}}}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,emqx,{bad_return,{{emqx_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{7,erl_parse,["syntax error before: ","']'"]}}},[{emqx_plugins,init_config,1,[{file,"emqx_plugins.erl"},{line,148}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{emqx_app,start,2,[{file,"emqx_app.erl"},{line,49}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,293}]}]}}}}})

Crash dump is being written to: log/crash.dump...done
root@9b9b28990650:/home/emqx/_build/emqx/rel/emqx/bin#`

**Comment by ULTRAKID** [comment]
是修改了所有插件配置文件的后缀，还是就kafka插件配置文件的后缀？你把配置文件的目录截个图吧

**Comment by allure11** [comment]
只修改了kafka的，需要全部修改吗
![image](https://github.com/ULTRAKID/emqx_plugin_kafka/assets/86544479/7285de7f-34d6-4f04-9a42-d878d1bde3c3)

**Comment by ULTRAKID** [comment]
> 只修改了kafka的，需要全部修改吗
> ![image](https://github.com/ULTRAKID/emqx_plugin_kafka/assets/86544479/7285de7f-34d6-4f04-9a42-d878d1bde3c3)
> 

就改kafka的就行。
你直接把这个仓库里的etc/emqx_plugin_kafka.config文件传到你的插件配置文件目录下，再修改里面的配置值试试，文件名不要动。
还不行的话你加我微信我远程帮你看一下

**Comment by allure11** [comment]
是配置文件问题，已解决，谢谢您

**Comment by ljp-Github-xl** [comment]
你好我也遇见了这个问题，报错信息如下，2025-07-15T21:41:38.162893+08:00 [alert] [Plugins] Plugin emqx_plugin_kafka load failed with {{schema_not_found,"/Users/apple/Documents/2024/emqx/emqx/_build/emqx/rel/emqx/lib/emqx_plugin_kafka-0.0.0+build.1.refe23cc37/priv/emqx_plugin_kafka.schema"},[{emqx_plugins,do_generate_configs,1,[{file,"emqx_plugins.erl"},{line,274}]},{emqx_plugins,load_plugin,2,[{file,"emqx_plugins.erl"},{line,299}]},{emqx_mgmt_api_plugins,load,2,[{file,"emqx_mgmt_api_plugins.erl"},{line,78}]},{minirest_handler,dispatch,2,[{file,"minirest_handler.erl"},{line,90}]},{minirest,handle_request,2,[{file,"minirest.erl"},{line,116}]},{minirest,init,2,[{file,"minirest.erl"},{line,108}]},{cowboy_handler,execute,2,[{file,"cowboy_handler.erl"},{line,41}]},{cowboy_stream_h,execute,3,[{file,"cowboy_stream_h.erl"},{line,320}]},{cowboy_stream_h,request_process,3,[{file,"cowboy_stream_h.erl"},{line,302}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}

**Comment by ljp-Github-xl** [comment]
@allure11 麻烦问一下，您这个问题如何解决的

**Comment by ULTRAKID** [comment]
> 你好我也遇见了这个问题，报错信息如下，2025-07-15T21:41:38.162893+08:00 [alert] [Plugins] Plugin emqx_plugin_kafka load failed with {{schema_not_found,"/Users/apple/Documents/2024/emqx/emqx/_build/emqx/rel/emqx/lib/emqx_plugin_kafka-0.0.0+build.1.refe23cc37/priv/emqx_plugin_kafka.schema"},[{emqx_plugins,do_generate_configs,1,[{file,"emqx_plugins.erl"},{line,274}]},{emqx_plugins,load_plugin,2,[{file,"emqx_plugins.erl"},{line,299}]},{emqx_mgmt_api_plugins,load,2,[{file,"emqx_mgmt_api_plugins.erl"},{line,78}]},{minirest_handler,dispatch,2,[{file,"minirest_handler.erl"},{line,90}]},{minirest,handle_request,2,[{file,"minirest.erl"},{line,116}]},{minirest,init,2,[{file,"minirest.erl"},{line,108}]},{cowboy_handler,execute,2,[{file,"cowboy_handler.erl"},{line,41}]},{cowboy_stream_h,execute,3,[{file,"cowboy_stream_h.erl"},{line,320}]},{cowboy_stream_h,request_process,3,[{file,"cowboy_stream_h.erl"},{line,302}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}

配置文件请使用最新版的https://github.com/ULTRAKID/emqx_plugin_kafka/blob/main/etc/emqx_plugin_kafka.config ，与旧版的emqx_plugin_kafka.conf配置格式不一样 @ljp-Github-xl

**Comment by ljp-Github-xl** [comment]
我现在用的配置文件和这个一样，日志报错是emqx/_build/emqx/rel/emqx/lib/emqx_plugin_kafka-0.0.0+build.1.refe23cc37/priv/emqx_plugin_kafka.schema，这个文件找不到，我make之后没有emqx_plugin_kafka.config这个文件，我是手动加入的，会是哪儿的问题呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ULTRAKID/emqx_plugin_kafka"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年7月15日(星期二) 晚上11:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ULTRAKID/emqx_plugin_kafka] 点击启用kafka插件报错 parse_config_file_failed (Issue #5)



ULTRAKID left a comment (ULTRAKID/emqx_plugin_kafka#5)
  
你好我也遇见了这个问题，报错信息如下，2025-07-15T21:41:38.162893+08:00 [alert] [Plugins] Plugin emqx_plugin_kafka load failed with {{schema_not_found,"/Users/apple/Documents/2024/emqx/emqx/_build/emqx/rel/emqx/lib/emqx_plugin_kafka-0.0.0+build.1.refe23cc37/priv/emqx_plugin_kafka.schema"},[{emqx_plugins,do_generate_configs,1,[{file,"emqx_plugins.erl"},{line,274}]},{emqx_plugins,load_plugin,2,[{file,"emqx_plugins.erl"},{line,299}]},{emqx_mgmt_api_plugins,load,2,[{file,"emqx_mgmt_api_plugins.erl"},{line,78}]},{minirest_handler,dispatch,2,[{file,"minirest_handler.erl"},{line,90}]},{minirest,handle_request,2,[{file,"minirest.erl"},{line,116}]},{minirest,init,2,[{file,"minirest.erl"},{line,108}]},{cowboy_handler,execute,2,[{file,"cowboy_handler.erl"},{line,41}]},{cowboy_stream_h,execute,3,[{file,"cowboy_stream_h.erl"},{line,320}]},{cowboy_stream_h,request_process,3,[{file,"cowboy_stream_h.erl"},{line,302}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
  
配置文件请使用最新版的https://github.com/ULTRAKID/emqx_plugin_kafka/blob/main/etc/emqx_plugin_kafka.config ，与旧版的emqx_plugin_kafka.conf配置格式不一样 @ljp-Github-xl

**Comment by ljp-Github-xl** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ULTRAKID/emqx_plugin_kafka"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年7月15日(星期二) 晚上11:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ULTRAKID/emqx_plugin_kafka] 点击启用kafka插件报错 parse_config_file_failed (Issue #5)



ULTRAKID left a comment (ULTRAKID/emqx_plugin_kafka#5)
  
你好我也遇见了这个问题，报错信息如下，2025-07-15T21:41:38.162893+08:00 [alert] [Plugins] Plugin emqx_plugin_kafka load failed with {{schema_not_found,"/Users/apple/Documents/2024/emqx/emqx/_build/emqx/rel/emqx/lib/emqx_plugin_kafka-0.0.0+build.1.refe23cc37/priv/emqx_plugin_kafka.schema"},[{emqx_plugins,do_generate_configs,1,[{file,"emqx_plugins.erl"},{line,274}]},{emqx_plugins,load_plugin,2,[{file,"emqx_plugins.erl"},{line,299}]},{emqx_mgmt_api_plugins,load,2,[{file,"emqx_mgmt_api_plugins.erl"},{line,78}]},{minirest_handler,dispatch,2,[{file,"minirest_handler.erl"},{line,90}]},{minirest,handle_request,2,[{file,"minirest.erl"},{line,116}]},{minirest,init,2,[{file,"minirest.erl"},{line,108}]},{cowboy_handler,execute,2,[{file,"cowboy_handler.erl"},{line,41}]},{cowboy_stream_h,execute,3,[{file,"cowboy_stream_h.erl"},{line,320}]},{cowboy_stream_h,request_process,3,[{file,"cowboy_stream_h.erl"},{line,302}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
  
配置文件请使用最新版的https://github.com/ULTRAKID/emqx_plugin_kafka/blob/main/etc/emqx_plugin_kafka.config ，与旧版的emqx_plugin_kafka.conf配置格式不一样 @ljp-Github-xl

**Comment by ULTRAKID** [comment]
@ljp-Github-xl 请确认插件版本是否是最新的，旧的插件版本使用旧版配置文件的格式，新的插件版本使用新版配置文件格式。另外确认一下配置文件放置的位置是否正确。

**Comment by ljp-Github-xl** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ULTRAKID/emqx_plugin_kafka"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年7月16日(星期三) 上午10:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ULTRAKID/emqx_plugin_kafka] 点击启用kafka插件报错 parse_config_file_failed (Issue #5)



ULTRAKID left a comment (ULTRAKID/emqx_plugin_kafka#5)
 
@ljp-Github-xl 请确认插件版本是否是最新的，旧的插件版本使用旧版配置文件的格式，新的插件版本使用新版配置文件格式。另外确认一下配置文件放置的位置是否正确。

**Comment by ljp-Github-xl** [comment]
您好，我发了一些关于版本和配置，以及代码分支的截图，您能看见吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年7月16日(周三) 上午10:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ULTRAKID/emqx_plugin_kafka] 点击启用kafka插件报错 parse_config_file_failed (Issue #5)


ULTRAKID left a comment (ULTRAKID/emqx_plugin_kafka#5)
 
@ljp-Github-xl 请确认插件版本是否是最新的，旧的插件版本使用旧版配置文件的格式，新的插件版本使用新版配置文件格式。另外确认一下配置文件放置的位置是否正确。

**Comment by ULTRAKID** [comment]
@ljp-Github-xl 看不见，建议使用GitHub网页进行回复

**Comment by ljp-Github-xl** [comment]
@ULTRAKID 

<img width="771" height="255" alt="Image" src="https://github.com/user-attachments/assets/7fc343f7-4d09-4154-abc9-7dcea89b9c54" />

<img width="774" height="566" alt="Image" src="https://github.com/user-attachments/assets/c60db555-c4e9-4bad-9658-45818db2c893" />

<img width="806" height="132" alt="Image" src="https://github.com/user-attachments/assets/8d674819-f843-4273-ae8b-70225da40698" />

**Comment by ULTRAKID** [comment]
@ljp-Github-xl 改一下文件后缀名，emqx_plugin_kafka.conf改为emqx_plugin_kafka.config（就改emqx_plugin_kafka这一个文件的后缀名）
